 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tryns", type: :request do
  # Tryn. As you add validations to Tryn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tryn.create! valid_attributes
      get tryns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tryn = Tryn.create! valid_attributes
      get tryn_url(tryn)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tryn_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tryn = Tryn.create! valid_attributes
      get edit_tryn_url(tryn)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tryn" do
        expect {
          post tryns_url, params: { tryn: valid_attributes }
        }.to change(Tryn, :count).by(1)
      end

      it "redirects to the created tryn" do
        post tryns_url, params: { tryn: valid_attributes }
        expect(response).to redirect_to(tryn_url(Tryn.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tryn" do
        expect {
          post tryns_url, params: { tryn: invalid_attributes }
        }.to change(Tryn, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tryns_url, params: { tryn: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tryn" do
        tryn = Tryn.create! valid_attributes
        patch tryn_url(tryn), params: { tryn: new_attributes }
        tryn.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tryn" do
        tryn = Tryn.create! valid_attributes
        patch tryn_url(tryn), params: { tryn: new_attributes }
        tryn.reload
        expect(response).to redirect_to(tryn_url(tryn))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tryn = Tryn.create! valid_attributes
        patch tryn_url(tryn), params: { tryn: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tryn" do
      tryn = Tryn.create! valid_attributes
      expect {
        delete tryn_url(tryn)
      }.to change(Tryn, :count).by(-1)
    end

    it "redirects to the tryns list" do
      tryn = Tryn.create! valid_attributes
      delete tryn_url(tryn)
      expect(response).to redirect_to(tryns_url)
    end
  end
end
